POST https://projeto-de-estudos-1-node-js.onrender.com/videos
Content-Type: application/json

{
    "title": "Video 1",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

GET https://projeto-de-estudos-1-node-js.onrender.com/videos


###

PUT https://projeto-de-estudos-1-node-js.onrender.com/videos/a873cc49-4319-4a53-a984-155585866908
Content-Type: application/json

{
    "title": "Video 3",
    "description": "Esse é o terceiro video AAAAAAA",
    "duration": 200
}

###

DELETE https://projeto-de-estudos-1-node-js.onrender.com/videos/fc6aa09b-7c83-4272-a4e5-223381a081d0